### ISSUE TITLE
"Couldn't extract video number and video title"

### ISSUE THREAD

**Issue by sliwma** [kosciolek/vider.info-downloader#2]
Hey, after trying to download any file even with solved Captcha, I get:
```
root@X1_Yoga_Win10:~# vider-dl https://vider.info/vid/+fxcx1n
Downloading https://vider.info/vid/+fxcx1n |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% || 0/100 Bytes || ETA: 0s/usr/local/lib/node_modules/@vider-downloader/cli/node_modules/@vider-downloader/core/dist/fetchVideoMetadata.js:71
                    throw new Error("Couldn't extract video number and video title.");
                          ^

Error: Couldn't extract video number and video title.
    at /usr/local/lib/node_modules/@vider-downloader/cli/node_modules/@vider-downloader/core/dist/fetchVideoMetadata.js:71:27
    at step (/usr/local/lib/node_modules/@vider-downloader/cli/node_modules/@vider-downloader/core/dist/fetchVideoMetadata.js:33:23)
    at Object.next (/usr/local/lib/node_modules/@vider-downloader/cli/node_modules/@vider-downloader/core/dist/fetchVideoMetadata.js:14:53)
    at fulfilled (/usr/local/lib/node_modules/@vider-downloader/cli/node_modules/@vider-downloader/core/dist/fetchVideoMetadata.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by kosciolek** [comment]
should work now, i wrote a new script
